#!/usr/bin/env bash
# Ignore shellcheck case SC2086
# You do not need to handle edge cases such as
# Empty parameters
# Nonexistent domain names
# Nonexistent subdomains

display_info()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];
    then
        display_info "$1" "$subdomain"
    fi
done
