#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
