#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
