#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
#+ The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo chgrp -R ubuntu /var/www/html
sudo chmod -R g+w /var/www/html

sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx stop

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default

sudo service nginx restart

