#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and hi at the position 9


i=1
while [ $i -le 10 ]
do
    if [ "$i" -eq 9 ]
    then
	echo "Holberton School"
	echo "Hi"
    else
	echo "Holberton School"
    fi
    ((i++))
done
