#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and hi at the position 9


i=1
while [ $i -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
