#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and hi at the position 9


i=0
while [ $i -le 19 ]
do
    (( i++ ))
    echo $i
    case $i in
    4)
        echo "back luck from China"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    ;;
    esac
done
