#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/temp_f
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/temp_f
cp -f ~/temp_f /etc/hosts
