#!/usr/bin/env bash
# a Bash script that creates an RSA key pair.
# Name of the created private key must be holberton
# Numberls of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

ssh-keygen -f holberton -b 4096 -N 'betty' -t 'rsa'
